### ISSUE TITLE
REQ plz add save data

### ISSUE THREAD

**Issue by lolminerxmrig** [T4t4ru/bookish-parakeet#1]
Hi.
REQ plz add save data

**Comment by lolminerxmrig** [comment]
can more item add.
openai
telegram
proxy
thanks.

**Comment by lolminerxmrig** [comment]
https://github.com/search?q=%2F%22sk-%5Ba-zA-Z0-9%5D%7B20%2C50%7D%22%2F%20language%3AShell%20&type=code

**Comment by T4t4ru** [comment]
done. I rewrote the code, use it

**Comment by lolminerxmrig** [comment]
all_scan.py -all
--- DATA COLLECTION ---
Traceback (most recent call last):
  File "C:\Users\Desktop\ZoomEye\bookish-parakeet\all_scan.py", line 94, in <module>
    output.extend(search_manager.search_api_keys(api_key_patterns, '', 1))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Desktop\ZoomEye\bookish-parakeet\all_scan.py", line 37, in search_api_keys
    raw_file_urls = self.github_api_search_code(query, page)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Desktop\ZoomEye\bookish-parakeet\all_scan.py", line 32, in github_api_search_code
    for item in response_json['items']:
                ~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'items'

**Comment by lolminerxmrig** [comment]
all_scan.py -openai
--- DATA COLLECTION ---
Traceback (most recent call last):
  File "C:\Users\Desktop\ZoomEye\bookish-parakeet\all_scan.py", line 97, in <module>
    if getattr(args, api):
       ^^^^^^^^^^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'bevigil'

**Comment by T4t4ru** [comment]
I rewrote the code while it's working, why it's not looking, I don't know, I'll think later when I have time for it, so expect when it will be
